apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-addresspool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.10.0 - 192.168.10.255

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-adv
  namespace: metallb-system
